-- Translation
hpname = "+"
reloadtip = "Tip: Press R to reload"
spec = "Spectator"
specmsg = "Spectatormodus"
no = "No"
yes = "Yes"
coinsname = "Kill-Coins"
closebtn = "Close"
sec_name = "Seconds"

-- Weapons and ammo
smg_buy = "SMG"
pistol_mun_buy = "Pistol-Ammo(20)"
shotgun_buy = "Shotgun"
shotgun_mun_buy = "Shotgun Ammo(20)"
smg_mun_buy = "SMG-Ammo"
mac_buy = "Mac 10"
mac_mun_buy = "Mac Ammo(30)"
rifle_buy = "Rifle"
rifle_mun_buy = "Rifle Ammo(6)"
car_buy = "Car"
weapon_name = "Weapon"

nocoins = "You dont have enough " .. coinsname .. " for buying this item!" 
entergame = "Enter game"
warn = "Warning"
shopname = "Shop"
cwin = "Counter Terrorists win"
twin = "Terrorists win"
noteam = "No one wins"
res = "Adwards"
langround = "Rounds Left"
langroundone = "Round"
nogame = "Enter game..."
round_end_title = "Runde beendet"
joinmsg = " has joined the game"
jointeam1 = " has joined "..team.GetName(1)
jointeam2 = " has joined "..team.GetName(2)
joinname = "Join "
changeteamname = "Change team"
buyname = "Buy"
itemtrans = "Item"
reporttitle = "Report a bug"
playername = "Players"
deathmsg = "You were killed by"